### ISSUE TITLE
Overflows on Mobile Version's 

### ISSUE THREAD

**Issue by ShreyanKhanna** [For-0/vocabustudy#238] opened 2022-11-16 02:51 UTC
There are a lot of Overflows on the Mobile side of the website.
I think this should be fixed but IDK if anyone started to work on this yet.

**Screenshots**

**Comment by grimsteel** [comment] 2022-11-16 02:53
Duplicate of #1

**Comment by grimsteel** [comment] 2022-11-16 02:53
Wow I just clicked too many buttons

**Closed by grimsteel** 2022-11-16 02:53 UTC
Labels: bug

**Comment by ShreyanKhanna** [comment] 2022-11-16 02:56
yes yes, u did, also do u want me to work on this if no one else is?

Also @grimsteel I have some other ideas for applications to put under for0, IDK what im supposed to do with them, cuz I've heard that vocabustudy needs coders, with the amount of bugs and things that are left, but I sorta don't ant to forget about them, so,,,

**Comment by ShreyanKhanna** [comment] 2022-11-16 02:56
but ill talk to u tmrw abt all this
